name: "CRON: alla SKUs i Magento"
on:
  schedule:
    - cron: '30 11 * * 1'

run-name: "CRON: All SKUs in Magneto (status=enabled, visibility=catalogAndSearch)"

jobs:
  test-all-skus-in-magento:
    name: test all skus in Magento
    timeout-minutes: 180
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright test
      run: npx playwright test github-actions-site.spec.ts --project chromium
      env:
        ENV_GITHUB_ACTION: ${{ vars.ENV_GITHUB_ACTION }}
        MAGENTO_BASE_URL: ${{ vars.MAGENTO_BASE_URL }}
        MAIL_TO: ${{ vars.MAIL_TO }}
        MAGENTO_TOKEN: ${{ secrets.MAGENTO_TOKEN }}
        SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
        run: echo ".ENV is populated"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: excel-report
        path: excel-reports/
        retention-days: 30
