name: "Manuellt: Testa kampanj"

on:
  workflow_dispatch:
    inputs:
      saleName:
        description: 'Ange ett namn för testet:'
        type: string
        required: true
      topRightBadge:
        description: 'Ange badgetext t.ex. "Deal" (lämna tomt om du vill testa att PDP inte har badge i övre högra hörnet)'
        type: string
      sendToSpecificEmails:
        description: "Skicka rapporten endast till följande emails (separera med kommatecken):"
        type: string

run-name: "Manuellt test: Kampanj - ${{ github.event.inputs.saleName }}"

jobs:
  ange-kampanj-info:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    outputs:
      skus: ${{ steps.set-sku.outputs.SKUS }}
      sale: ${{ steps.set-sale.outputs.SALE }}
      slp: ${{ steps.set-slp.outputs.SLP }}
      qty: ${{ steps.set-qty.outputs.QTY }}
    steps:
      - name: Interactive inputs step
        id: kampanj-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_TOKEN }}
          timeout: 160
          title: "Klistra in kampanjinfo"
          interactive: |
            fields:
              - label: skus
                properties:
                  type: textarea
                  display: "Klistra in SKUs att testa:"
                  placeholder: "Måste anges"
                  required: true
              - label: sale
                properties:
                  type: textarea
                  display: "Klistra in Kampanjpriser:"
                  placeholder: "Priser från PLP kommer användas om kampanjpriser ej anges"
              - label: slp
                properties:
                  type: textarea
                  display: "Klistra in SLPs:"
                  placeholder: "Priser från PLP kommer användas om SLPs ej anges"
              - label: qty
                properties:
                  type: boolean
                  display: "Testa med lagersaldo:"
                  defaultValue: true
      - id: set-sku
        run: |
          echo "SKUS<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.skus }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - id: set-sale
        run: |
          echo "SALE<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.sale }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - id: set-slp
        run: |
          echo "SLP<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.slp }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - id: set-qty
        run: |
          echo "QTY<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.qty }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  testa-kampanj:
    needs: ange-kampanj-info
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright kampanj test
      run: npx playwright test github-actions-kampanj.spec.ts --project chromium
      env:
        ENV_GITHUB_ACTION: ${{ vars.ENV_GITHUB_ACTION }}
        MAGENTO_BASE_URL: ${{ vars.MAGENTO_BASE_URL }}
        SALE_NAME: ${{ github.event.inputs.saleName }}
        TOP_RIGHT_BADGE: ${{ github.event.inputs.topRightBadge }}
        SKUS: ${{ needs.ange-kampanj-info.outputs.skus }}
        SALE_PRICES: ${{ needs.ange-kampanj-info.outputs.sale }}
        SLP: ${{ needs.ange-kampanj-info.outputs.slp }}
        QTY: ${{ needs.ange-kampanj-info.outputs.qty }}
        SINGLE_MAIL_TO: ${{ github.event.inputs.sendToSpecificEmails }}
        MAIL_TO: ${{ vars.MAIL_TO }}
        MAGENTO_TOKEN: ${{ secrets.MAGENTO_TOKEN }}
        SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 2
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: excel-report
        path: excel-reports/
        retention-days: 30
