name: "Manuellt: Kategori"
on:
  workflow_dispatch:
    inputs:
      targetCategory:
        description: "Välj en kategori att testa:"
        type: choice
        options:
        - Accessoarer
        - Byxor
        - Jackor & Rockar
        - Jeans
        - Kavajer
        - Kostymbyxor
        - Kostymvästar
        - Flanell
        - Shorts
        - Skjortor
        - Sweats
        - T-shirts & Pikéer
        - Tröjor
        - Underkläder
        - Koftor & cardigans
        - Kostym
        required: true
      removeOutOfStockAndChildless:
        description: Ta bort SKUs som inte kan synas på hemsidan (ingen effekt för kostymer pga RNBs)
        type: choice
        options:
        - "true"
        - "false"
        default: "true"
      sendReportToOneEmail:
        description: "Skicka rapport endast till den email du skriver in här:"
        type: string

run-name: "Manuellt test: Kategori - ${{ github.event.inputs.targetCategory }}, ta bort SKUs som inte kan synas på hemsidan=${{ github.event.inputs.removeOutOfStockAndChildless }}"

jobs:
  playwright-test:
    name: test ${{ github.event.inputs.targetCategory }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright Kategori test
      run: npx playwright test kategori.spec.ts --project chromium
      env:
        CATEGORY_UNDER_TEST: ${{ github.event.inputs.targetCategory }}
        REMOVE_SKUS: ${{ github.event.inputs.removeOutOfStockAndChildless }}
        ENV_GITHUB_ACTION: ${{ vars.ENV_GITHUB_ACTION }}
        MAGENTO_BASE_URL: ${{ vars.MAGENTO_BASE_URL }}
        MAIL_TO: ${{ vars.MAIL_TO }}
        SINGLE_MAIL_TO: ${{ github.event.inputs.sendReportToOneEmail }}
        MAGENTO_TOKEN: ${{ secrets.MAGENTO_TOKEN }}
        SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
        run: echo ".ENV is populated"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: excel-report
        path: excel-reports/
        retention-days: 30