name: Manually - test Categories
on:
  workflow_dispatch:
    inputs:
      targetCategory:
        description: Choose 1 category to test
        type: choice
        options:
        - Accessoarer
        - Byxor
        - Jackor & Rockar
        - Jeans
        - Kavajer
        - Kostymbyxor
        - Kostymvästar
        - Flanell
        - Shorts
        - Skjortor
        - Sweats
        - T-shirts & Pikéer
        - Tröjor
        - Underkläder
        - Koftor & cardigans
        - Kostym
        required: true
jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright Kategori test
      run: npx playwright test kategori
      env:
        MAGENTO_TOKEN: ${{ secrets.MAGENTO_TOKEN }}
        MAGENTO_BASE_URL: ${{ vars.MAGENTO_BASE_URL }}
        SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
        CATEGORY_UNDER_TEST: ${{ github.event.inputs.targetCategory }}
        run: echo ".ENV is populated"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
