name: "Manuellt: Testa kampanj"

on:
  workflow_dispatch:
    inputs:
      saleName:
        description: 'Namn för testet (används i rapportfilnamnet):'
        type: string
        required: true
      # skus:
      #   description: "Copy/paste:a in SKUs som du vill testa här"
      #   type: string
      #   required: true
      # salePrices:
      #   description: "KAMPANJPRISER (Utan kampanjpriser kommer PLP användas för att testa PDP):"
      #   type: string
      # slps:
      #   description: "SLPs (Utan SLPs kommer PLP användas för att testa PDP):"
      #   type: string
      sendReportToOneEmail:
        description: "Skicka rapport endast till den email du skriver in här:"
        type: string

run-name: "Manuellt test: Kampanj - ${{ github.event.inputs.saleName }}"

jobs:
  kampanj-info:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Interactive inputs step
        id: interactive-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_TOKEN }}
          timeout: 160
          title: "Klistra in kampanjinfo"
          interactive: |
            fields:
              - label: skus
                properties:
                  type: textarea
                  display: "Klistra in SKUs att testa:"
              - label: sale
                properties:
                  type: textarea
                  display: "Klistra in Kampanjpriser:"
              - label: slp
                properties:
                  type: textarea
                  display: "Klistra in SLPs:"
      - name: Set interactive-inputs as github ENVs
        run: |
          echo "SKUS=${{ steps.interactive-inputs.outputs.continue-roll-out.skus }}" >> $GITHUB_ENV
          echo "SALE=${{ steps.interactive-inputs.outputs.continue-roll-out.sale }}" >> $GITHUB_ENV
          echo "SLP=${{ steps.interactive-inputs.outputs.continue-roll-out.slp }}" >> $GITHUB_ENV
      - name: echo stored values
        run: echo "${{ steps.interactive-inputs.outputs }}"
  kampanj:
    needs: kampanj-info
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright kampanj test
      run: npx playwright test selected-skus.spec.ts --project chromium
      env:
        ENV_GITHUB_ACTION: ${{ vars.ENV_GITHUB_ACTION }}
        MAGENTO_BASE_URL: ${{ vars.MAGENTO_BASE_URL }}
        SALE_NAME: ${{ github.event.inputs.saleName }}
        # SKUS: ${{ github.event.inputs.skus }}
        # SALE_PRICES: ${{ github.event.inputs.salePrices }}
        # SLP: ${{ github.event.inputs.slps }}
        SKUS: echo "${{ env.SKUS }}"
        SALE_PRICES: echo "${{ env.SALE_PRICES }}"
        SLP: echo "${{ env.SLP }}"
        SINGLE_MAIL_TO: ${{ github.event.inputs.sendReportToOneEmail }}
        MAIL_TO: ${{ vars.MAIL_TO }}
        MAGENTO_TOKEN: ${{ secrets.MAGENTO_TOKEN }}
        SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
        run: echo ".ENV is populated"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: excel-report
        path: excel-reports/
        retention-days: 1

  