name: "Manuellt: Testa kampanj"

on:
  workflow_dispatch

run-name: "Manuellt test: Kampanj - ${{ github.event.inputs.saleName }}"

jobs:
  ange-kampanj-info:
    timeout-minutes: 3
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    outputs:
      name: ${{ steps.set-name.outputs.NAME }}
      email: ${{ steps.set-email.outputs.EMAIL }}
      skus: ${{ steps.set-sku.outputs.SKUS }}
      sale: ${{ steps.set-sale.outputs.SALE }}
      slp: ${{ steps.set-slp.outputs.SLP }}
    steps:
      - name: Interactive inputs step
        id: kampanj-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_TOKEN }}
          timeout: 160
          title: "Klistra in kampanjinfo"
          interactive: |
            fields:
              - label: name
                properties:
                  type: text
                  display: "Rapportnamn:"
                  required: true
              - label: email
                properties:
                  type: text
                  display: Skicka rapporten endast till:
                  placeholder: 'separera emails med "," t.ex. mail1@mail.com,mail2@mail.com'
              - label: skus
                properties:
                  type: textarea
                  display: "Klistra in SKUs att testa:"
                  required: true
              - label: sale
                properties:
                  type: textarea
                  display: "Klistra in Kampanjpriser:"
              - label: slp
                properties:
                  type: textarea
                  display: "Klistra in SLPs:"
      - id: set-name
        run: |
          echo "NAME<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.name }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - id: set-email
        run: |
          echo "EMAIL<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.email }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - id: set-sku
        run: |
          echo "SKUS<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.skus }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - id: set-sale
        run: |
          echo "SALE<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.sale }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - id: set-slp
        run: |
          echo "SLP<<EOF" >>$GITHUB_OUTPUT
          echo "${{ steps.kampanj-inputs.outputs.slp }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  kampanj:
    needs: ange-kampanj-info
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright kampanj test
      run: npx playwright test selected-skus.spec.ts --project chromium
      env:
        ENV_GITHUB_ACTION: ${{ vars.ENV_GITHUB_ACTION }}
        MAGENTO_BASE_URL: ${{ vars.MAGENTO_BASE_URL }}
        SALE_NAME: ${{ needs.ange-kampanj-info.outputs.name }}
        SKUS: ${{ needs.ange-kampanj-info.outputs.skus }}
        SALE_PRICES: ${{ needs.ange-kampanj-info.outputs.sale }}
        SLP: ${{ needs.ange-kampanj-info.outputs.slp }}
        SINGLE_MAIL_TO: ${{ needs.ange-kampanj-info.outputs.email }}
        MAIL_TO: ${{ vars.MAIL_TO }}
        MAGENTO_TOKEN: ${{ secrets.MAGENTO_TOKEN }}
        SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: excel-report
        path: excel-reports/
        retention-days: 1

  