name: "Manuellt: Testa kampanj"

on:
  workflow_dispatch:
    inputs:
      saleName:
        description: 'Namn för testet (används i rapportfilnamnet):'
        type: string
        required: true
      # skus:
      #   description: "Copy/paste:a in SKUs som du vill testa här"
      #   type: string
      #   required: true
      # salePrices:
      #   description: "KAMPANJPRISER (Utan kampanjpriser kommer PLP användas för att testa PDP):"
      #   type: string
      # slps:
      #   description: "SLPs (Utan SLPs kommer PLP användas för att testa PDP):"
      #   type: string
      sendReportToOneEmail:
        description: "Skicka rapport endast till den email du skriver in här:"
        type: string

run-name: "Manuellt test: Kampanj - ${{ github.event.inputs.saleName }}"

jobs:
  skriv-in-kampanj-info:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    # outputs:
    #   skus: ${{ steps.kampanj-inputs.outputs.SKUS }}
    #   sale: ${{ steps.kampanj-inputs.outputs.SALE }}
    #   slp: ${{ steps.kampanj-inputs.outputs.SLP }}
    steps:
      - name: Interactive inputs step
        id: kampanj-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_TOKEN }}
          timeout: 160
          title: "Klistra in kampanjinfo"
          interactive: |
            fields:
              - label: skus
                properties:
                  type: textarea
                  display: "Klistra in SKUs att testa:"
              - label: sale
                properties:
                  type: textarea
                  display: "Klistra in Kampanjpriser:"
              - label: slp
                properties:
                  type: textarea
                  display: "Klistra in SLPs:"
      - name: Set SKUS
        id: set-sku
        uses: noobly314/share-data@v1
        with:
          share-id: share_skus
          mode: set
          key: sku
          value: ${{steps.kampanj-inputs.outputs.skus }}
      - name: Set SALE PRICES
        id: set-sale
        uses: noobly314/share-data@v1
        with:
          share-id: share_sale
          mode: set
          key: sale
          value: ${{steps.kampanj-inputs.outputs.sale }}
      - name: Set SLP
        id: set-slp
        uses: noobly314/share-data@v1
        with:
          share-id: share_slp
          mode: set
          key: slp
          value: ${{steps.kampanj-inputs.outputs.slp }}
  kampanj:
    needs: skriv-in-kampanj-info
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Get SKUS
      id: get_skus
      uses: noobly314/share-data@v1
      with:
        share-id: skus_id
        mode: get
        key: skus
    - name: Get SALE PRICES
      id: get_sale
      uses: noobly314/share-data@v1
      with:
        share-id: sale_id
        mode: get
        key: sale
    - name: Get SLP
      id: get_slp
      uses: noobly314/share-data@v1
      with:
        share-id: slp_id
        mode: get
        key: slp
    - name: output passed vars
      run: echo ${{ steps.get_skus.outputs.data.skus }}
    - name: Run Playwright kampanj test
      run: npx playwright test selected-skus.spec.ts --project chromium
      env:
        ENV_GITHUB_ACTION: ${{ vars.ENV_GITHUB_ACTION }}
        MAGENTO_BASE_URL: ${{ vars.MAGENTO_BASE_URL }}
        SALE_NAME: ${{ github.event.inputs.saleName }}
        SKUS: ${{ steps.get_skus.outputs.data }}
        SALE_PRICES: ${{ steps.get_sale.outputs.data }}
        SLP: ${{ steps.get_slp.outputs.data }}
        SINGLE_MAIL_TO: ${{ github.event.inputs.sendReportToOneEmail }}
        MAIL_TO: ${{ vars.MAIL_TO }}
        MAGENTO_TOKEN: ${{ secrets.MAGENTO_TOKEN }}
        SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
        run: echo ".ENV is populated"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: excel-report
        path: excel-reports/
        retention-days: 1